# this docker-compose must run on the Master node
# Slave nodes must have at least Java 8 installed
# see https://wiki.jenkins.io/display/JENKINS/Distributed+builds

version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine # official image
    ports:
      - '8080:8080' # by default runs on that port
      - '50000:50000' # Master/Slave communication
    volumes:
      - jenkins_home:/var/jenkins_home # persist data of Jenkins
    restart: always

volumes:
  jenkins_home:
